import type { Metadata } from 'next'
import { GoogleOAuthProvider } from '@react-oauth/google'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import './reset.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

// Google Client Id
const ClientId =
  '246885474721-45d51ac88psutifbi0mnf7ssqv7j3tpb.apps.googleusercontent.com'

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <GoogleOAuthProvider clientId={ClientId}>
      <html lang="en" className="bg-black">
        <body>{children}</body>
      </html>
    </GoogleOAuthProvider>
  )
}
